# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: airline_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"