server:
  port: 8761

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

gateway:
  discovery:
    locator:
      enabled: true
      lower-case-service-id: true

  routes:
    - id: user-service-route
      uri: lb://user-service
      predicates:
        - Path=/users/**
      filters:
        - RewritePath=/users/(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG